### ISSUE TITLE
This is amazing

### ISSUE THREAD

**Issue by ghost** [gnmmarechal/frankenupdater#2]
![s1txtw7](https://cloud.githubusercontent.com/assets/19160014/15025377/e6997288-1230-11e6-8787-509a1acf0539.jpg)
1. Makes FrankenFW updater that has a higher chance of bricking than the others. Because it doesnt actually check Hashes for file corruption.
2. Knows it has a brick chance so recommends being on A9LH/Nand Backup/Harmod

Aka you need to be on a Firmware that doesnt need to be FrankenUpdated to use the updater safely.

Only 9.2 and below can nand backup in which you cna have Emunand on latest FW
If you have A9LH you dont need Frakenfirmware as you are on latest
If you have a hardmod you wont need frankenfirmware as you can get the above easily without and chance of bricks.

**I AM SPECIAL ROUND 2 ELECTRIC BOOGALOO**

**Comment by gnmmarechal** [comment]
ffs. I'm not sure this works. Which is why I want someone to test it and that person should have a hardmod/A9LH. If it is confirmed working, I'll remove that sentence.
Got it? Stop posting "issues" that aren't issues. Ok? It's stupid, you're only wasting your time.
